on: [push, pull_request]

name: CI

jobs:
  CI:
    name: Production build
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: file:./ci.sqlite
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 20.19.0
          package-manager-cache: false

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript type checking
        if: ${{ !startsWith(github.head_ref || github.ref_name, 'javascript') }}
        run: npx tsc --noEmit

      - name: Run ESLint
        run: npm run lint

      - name: Validate Prisma
        run: npx prisma generate && npx prisma validate

      - name: Build application
        run: npm run build
